//! LLM provider abstraction.
//!
//! Defines the [`LlmProvider`] trait and types for chat-based LLM
//! interactions. The trait returns `Pin<Box<dyn Future>>` for dyn-safety
//! so providers can be shared as `Arc<dyn LlmProvider>`.
//!
//! [`AgentBehavior`](crate::agent::AgentBehavior) stays generic (RPITIT)
//! for zero-cost dispatch in the hot actor loop.

mod openrouter;

pub use openrouter::OpenRouterClient;

use std::future::Future;
use std::pin::Pin;

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::error::LlmError;
use crate::tool::ToolSpec;

/// Role in a chat conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// System prompt providing instructions to the model.
    System,
    /// User-supplied input.
    User,
    /// Model-generated response.
    Assistant,
    /// Result of a tool invocation, correlated by `tool_call_id`.
    Tool,
}

/// A tool call requested by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Provider-assigned call ID, used to correlate tool results.
    pub id: String,
    /// Name of the tool to invoke (must match a registered [`ToolSpec`]).
    pub name: String,
    /// JSON arguments parsed from the model's function call output.
    pub arguments: Value,
}

/// A single message in a chat conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// Who produced this message.
    pub role: Role,
    /// Text content of the message.
    pub content: String,
    /// Tool calls requested by the assistant (empty for non-assistant roles).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_calls: Vec<ToolCall>,
    /// ID of the tool call this message is responding to (`Tool` role only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
}

/// Request payload for an LLM chat completion.
///
/// `model` is optional — if `None`, the provider uses its configured default.
#[derive(Debug, Clone)]
pub struct LlmRequest {
    /// Model identifier override (`None` = provider default).
    pub model: Option<String>,
    /// Conversation history.
    pub messages: Vec<ChatMessage>,
    /// Sampling temperature (`None` = provider default).
    pub temperature: Option<f32>,
    /// Maximum tokens to generate (`None` = provider default).
    pub max_tokens: Option<u32>,
    /// Tool definitions available for this call (`None` = no tools).
    pub tools: Option<Vec<ToolSpec>>,
}

/// Response from an LLM chat completion.
#[derive(Debug, Clone)]
pub struct LlmResponse {
    /// Text content of the assistant's reply.
    pub content: String,
    /// Tokens consumed by the prompt (input).
    pub prompt_tokens: u64,
    /// Tokens generated by the model (output).
    pub completion_tokens: u64,
    /// Tool calls the model wants executed (empty if none).
    pub tool_calls: Vec<ToolCall>,
}

impl LlmResponse {
    /// Total tokens consumed (prompt + completion).
    pub fn total_tokens(&self) -> u64 {
        self.prompt_tokens + self.completion_tokens
    }
}

/// Trait for LLM provider implementations.
///
/// Returns `Pin<Box<dyn Future>>` for dyn-safety — allows `Arc<dyn LlmProvider>`.
/// The per-call boxing cost is negligible relative to network I/O.
pub trait LlmProvider: Send + Sync + 'static {
    /// Sends a chat completion request and returns the response.
    fn chat<'a>(
        &'a self,
        request: &'a LlmRequest,
    ) -> Pin<Box<dyn Future<Output = Result<LlmResponse, LlmError>> + Send + 'a>>;
}
