//! LLM provider abstraction.
//!
//! Defines the [`LlmProvider`] trait and types for chat-based LLM
//! interactions. The trait returns `Pin<Box<dyn Future>>` for dyn-safety
//! so providers can be shared as `Arc<dyn LlmProvider>`.
//!
//! [`AgentBehavior`](crate::agent::AgentBehavior) stays generic (RPITIT)
//! for zero-cost dispatch in the hot actor loop.

mod openrouter;

pub use openrouter::{OpenRouterClient, OpenRouterClientBuilder, OpenRouterClientBuilderInit};

use std::future::Future;
use std::pin::Pin;

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::error::LlmError;
use crate::tool::ToolSpec;

/// Role in a chat conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// System prompt providing instructions to the model.
    System,
    /// User-supplied input.
    User,
    /// Model-generated response.
    Assistant,
    /// Result of a tool invocation, correlated by `tool_call_id`.
    Tool,
}

/// A tool call requested by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Provider-assigned call ID, used to correlate tool results.
    pub id: String,
    /// Name of the tool to invoke (must match a registered [`ToolSpec`]).
    pub name: String,
    /// JSON arguments parsed from the model's function call output.
    pub arguments: Value,
}

/// A single message in a chat conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    /// Who produced this message.
    pub role: Role,
    /// Text content of the message.
    pub content: String,
    /// Tool calls requested by the assistant (empty for non-assistant roles).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_calls: Vec<ToolCall>,
    /// ID of the tool call this message is responding to (`Tool` role only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
}

/// Request payload for an LLM chat completion.
///
/// `model` is optional — if `None`, the provider uses its configured default.
#[derive(Debug, Clone)]
pub struct LlmRequest {
    /// Model identifier override (`None` = provider default).
    pub model: Option<String>,
    /// Conversation history.
    pub messages: Vec<ChatMessage>,
    /// Sampling temperature (`None` = provider default).
    pub temperature: Option<f32>,
    /// Maximum tokens to generate (`None` = provider default).
    pub max_tokens: Option<u32>,
    /// Tool definitions available for this call (`None` = no tools).
    pub tools: Option<Vec<ToolSpec>>,
}

impl LlmRequest {
    /// Returns a builder for constructing an [`LlmRequest`].
    pub fn builder() -> LlmRequestBuilder {
        LlmRequestBuilder {
            messages: Vec::new(),
            model: None,
            temperature: None,
            max_tokens: None,
            tools: None,
        }
    }
}

/// Builder for [`LlmRequest`] with sensible defaults.
///
/// All fields except `messages` default to `None`.
#[derive(Debug)]
pub struct LlmRequestBuilder {
    messages: Vec<ChatMessage>,
    model: Option<String>,
    temperature: Option<f32>,
    max_tokens: Option<u32>,
    tools: Option<Vec<ToolSpec>>,
}

impl LlmRequestBuilder {
    /// Sets the full list of conversation messages.
    pub fn messages(mut self, messages: Vec<ChatMessage>) -> Self {
        self.messages = messages;
        self
    }

    /// Appends a single message to the conversation.
    pub fn message(mut self, message: ChatMessage) -> Self {
        self.messages.push(message);
        self
    }

    /// Sets the model identifier (overrides provider default).
    pub fn model(mut self, model: impl Into<String>) -> Self {
        self.model = Some(model.into());
        self
    }

    /// Sets the sampling temperature.
    pub fn temperature(mut self, temp: f32) -> Self {
        self.temperature = Some(temp);
        self
    }

    /// Sets the maximum number of tokens to generate.
    pub fn max_tokens(mut self, tokens: u32) -> Self {
        self.max_tokens = Some(tokens);
        self
    }

    /// Sets the tool definitions available for this call.
    pub fn tools(mut self, tools: Vec<ToolSpec>) -> Self {
        self.tools = Some(tools);
        self
    }

    /// Consumes the builder and produces an [`LlmRequest`].
    pub fn build(self) -> LlmRequest {
        LlmRequest {
            model: self.model,
            messages: self.messages,
            temperature: self.temperature,
            max_tokens: self.max_tokens,
            tools: self.tools,
        }
    }
}

/// Response from an LLM chat completion.
#[derive(Debug, Clone)]
pub struct LlmResponse {
    /// Text content of the assistant's reply.
    pub content: String,
    /// Tokens consumed by the prompt (input).
    pub prompt_tokens: u64,
    /// Tokens generated by the model (output).
    pub completion_tokens: u64,
    /// Tool calls the model wants executed (empty if none).
    pub tool_calls: Vec<ToolCall>,
}

impl LlmResponse {
    /// Total tokens consumed (prompt + completion).
    pub fn total_tokens(&self) -> u64 {
        self.prompt_tokens + self.completion_tokens
    }
}

/// A simple `Stream` adapter over a `Vec` iterator. Used by the default
/// `chat_stream` implementation to avoid pulling in extra crates.
struct VecStream<I: Iterator + Unpin + Send> {
    items: I,
}

impl<I: Iterator + Unpin + Send> futures_core::Stream for VecStream<I> {
    type Item = I::Item;

    fn poll_next(
        mut self: Pin<&mut Self>,
        _cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        std::task::Poll::Ready(self.items.next())
    }
}

/// A single chunk from a streaming LLM response.
#[derive(Debug, Clone)]
pub enum StreamChunk {
    /// A text delta — a partial token from the LLM.
    Delta(String),
    /// The final message with complete token usage.
    Done(LlmResponse),
}

/// Boxed stream of [`StreamChunk`]s for object-safe streaming.
pub type LlmStream = Pin<Box<dyn futures_core::Stream<Item = Result<StreamChunk, LlmError>> + Send>>;

/// Trait for LLM provider implementations.
///
/// Returns `Pin<Box<dyn Future>>` for dyn-safety — allows `Arc<dyn LlmProvider>`.
/// The per-call boxing cost is negligible relative to network I/O.
pub trait LlmProvider: Send + Sync + 'static {
    /// Sends a chat completion request and returns the response.
    fn chat<'a>(
        &'a self,
        request: &'a LlmRequest,
    ) -> Pin<Box<dyn Future<Output = Result<LlmResponse, LlmError>> + Send + 'a>>;

    /// Sends a chat completion request and returns a stream of chunks.
    ///
    /// The default implementation calls [`chat()`](Self::chat), waits for the
    /// full response, then yields the content as a single [`StreamChunk::Delta`]
    /// followed by [`StreamChunk::Done`].
    ///
    /// Providers that support native streaming (e.g. OpenRouter SSE) should
    /// override this to yield incremental deltas.
    fn chat_stream<'a>(
        &'a self,
        request: &'a LlmRequest,
    ) -> Pin<Box<dyn Future<Output = Result<LlmStream, LlmError>> + Send + 'a>> {
        Box::pin(async move {
            let response = self.chat(request).await?;
            let items: Vec<Result<StreamChunk, LlmError>> = vec![
                Ok(StreamChunk::Delta(response.content.clone())),
                Ok(StreamChunk::Done(response)),
            ];
            Ok(Box::pin(VecStream { items: items.into_iter() }) as LlmStream)
        })
    }
}
