//! Session persistence for multi-turn agent conversations.
//!
//! [`SessionStore`] is the storage abstraction. [`MemorySessionStore`] is the
//! in-process default used in CLI mode and tests. [`FileSessionStore`] (added
//! in a subsequent issue) is the default for HTTP server mode.

use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use thiserror::Error;
use tokio::sync::Mutex;

use crate::llm::{ChatMessage, Role as LlmRole};

// ── Error ─────────────────────────────────────────────────────────────────────

/// Errors from session store operations.
#[derive(Debug, Error)]
pub enum SessionError {
    /// An I/O error (file-backed stores).
    #[error("session I/O error: {0}")]
    Io(#[from] std::io::Error),
    /// A serialization or deserialization error.
    #[error("session serialization error: {0}")]
    Serialization(String),
    /// Any other store-specific error.
    #[error("session store error: {0}")]
    Other(String),
}

// ── Role ─────────────────────────────────────────────────────────────────────

/// Role of a participant in a stored conversation turn.
///
/// Only the three conversation roles are stored — tool call round-trips
/// are transient and not persisted.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// A message authored by the human user.
    User,
    /// A message generated by the assistant.
    Assistant,
    /// A system prompt injected before the conversation.
    System,
}

impl From<Role> for LlmRole {
    fn from(r: Role) -> Self {
        match r {
            Role::User => LlmRole::User,
            Role::Assistant => LlmRole::Assistant,
            Role::System => LlmRole::System,
        }
    }
}

// ── Message ───────────────────────────────────────────────────────────────────

/// A single stored conversation turn.
///
/// Maps 1:1 to the `messages` array sent to the LLM provider.
/// Tool call round-trips are not stored — only the final text turns are.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Who produced this turn.
    pub role: Role,
    /// Text content of the turn.
    pub content: String,
}

impl Message {
    /// Converts this stored message into a [`ChatMessage`] suitable for LLM requests.
    pub fn to_chat_message(&self) -> ChatMessage {
        ChatMessage {
            role: self.role.clone().into(),
            content: self.content.clone(),
            tool_calls: vec![],
            tool_call_id: None,
        }
    }
}

// ── SessionStore trait ────────────────────────────────────────────────────────

/// Pluggable storage backend for conversation history.
///
/// Implementors can back this with in-memory state, files, Redis, Postgres,
/// or any async store. The trait uses `Pin<Box<dyn Future>>` for object safety.
///
/// Built-in implementations:
/// - [`MemorySessionStore`] — in-process `HashMap`, used for CLI and tests.
/// - `FileSessionStore` — one JSON file per session, used for HTTP server mode.
pub trait SessionStore: Send + Sync + 'static {
    /// Loads the conversation history for `session_id`.
    ///
    /// Returns an empty `Vec` if the session does not exist.
    fn load<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<Message>, SessionError>> + Send + 'a>>;

    /// Persists the conversation history for `session_id`.
    ///
    /// Overwrites any existing history for this session.
    fn save<'a>(
        &'a self,
        session_id: &'a str,
        history: &'a [Message],
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>>;

    /// Removes all stored history for `session_id`.
    ///
    /// Does nothing if the session does not exist.
    fn delete<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>>;
}

// ── MemorySessionStore ────────────────────────────────────────────────────────

/// In-memory session store backed by a `HashMap`.
///
/// The default for CLI mode and tests. Sessions are lost when the process exits.
#[derive(Debug, Default)]
pub struct MemorySessionStore {
    inner: Arc<Mutex<HashMap<String, Vec<Message>>>>,
}

impl MemorySessionStore {
    /// Creates a new, empty in-memory session store.
    pub fn new() -> Self {
        Self::default()
    }
}

impl SessionStore for MemorySessionStore {
    fn load<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<Message>, SessionError>> + Send + 'a>> {
        Box::pin(async move {
            let map = self.inner.lock().await;
            Ok(map.get(session_id).cloned().unwrap_or_default())
        })
    }

    fn save<'a>(
        &'a self,
        session_id: &'a str,
        history: &'a [Message],
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>> {
        Box::pin(async move {
            let mut map = self.inner.lock().await;
            map.insert(session_id.to_string(), history.to_vec());
            Ok(())
        })
    }

    fn delete<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>> {
        Box::pin(async move {
            let mut map = self.inner.lock().await;
            map.remove(session_id);
            Ok(())
        })
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn msg(role: Role, content: &str) -> Message {
        Message { role, content: content.into() }
    }

    #[tokio::test]
    async fn memory_store_load_save_delete_round_trip() {
        let store = MemorySessionStore::new();

        // Load non-existent session → empty vec
        let history = store.load("s1").await.unwrap();
        assert!(history.is_empty());

        // Save a conversation
        let turns = vec![
            msg(Role::User, "Hello"),
            msg(Role::Assistant, "Hi there!"),
        ];
        store.save("s1", &turns).await.unwrap();

        // Load it back
        let loaded = store.load("s1").await.unwrap();
        assert_eq!(loaded.len(), 2);
        assert_eq!(loaded[0].content, "Hello");
        assert_eq!(loaded[1].content, "Hi there!");

        // Different session is independent
        let other = store.load("s2").await.unwrap();
        assert!(other.is_empty());

        // Delete
        store.delete("s1").await.unwrap();
        let after_delete = store.load("s1").await.unwrap();
        assert!(after_delete.is_empty());

        // Delete non-existent is a no-op
        store.delete("s99").await.unwrap();
    }

    #[test]
    fn message_converts_to_chat_message() {
        let m = msg(Role::User, "test");
        let cm = m.to_chat_message();
        assert!(matches!(cm.role, LlmRole::User));
        assert_eq!(cm.content, "test");
        assert!(cm.tool_calls.is_empty());
    }
}
