//! Session persistence for multi-turn agent conversations.
//!
//! [`SessionStore`] is the storage abstraction. [`MemorySessionStore`] is the
//! in-process default used in CLI mode and tests. [`FileSessionStore`] is the
//! default for HTTP server mode, persisting one JSON file per session.

use std::collections::HashMap;
use std::future::Future;
use std::path::{Path, PathBuf};
use std::pin::Pin;
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use thiserror::Error;
use tokio::sync::Mutex;

use crate::llm::{ChatMessage, Role as LlmRole};

// ── Error ─────────────────────────────────────────────────────────────────────

/// Errors from session store operations.
#[derive(Debug, Error)]
pub enum SessionError {
    /// An I/O error (file-backed stores).
    #[error("session I/O error: {0}")]
    Io(#[from] std::io::Error),
    /// A serialization or deserialization error.
    #[error("session serialization error: {0}")]
    Serialization(String),
    /// An invalid session ID (e.g. contains path traversal characters).
    #[error("invalid session ID: {0}")]
    Invalid(String),
    /// Any other store-specific error.
    #[error("session store error: {0}")]
    Other(String),
}

// ── Role ─────────────────────────────────────────────────────────────────────

/// Role of a participant in a stored conversation turn.
///
/// Only the three conversation roles are stored — tool call round-trips
/// are transient and not persisted.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// A message authored by the human user.
    User,
    /// A message generated by the assistant.
    Assistant,
    /// A system prompt injected before the conversation.
    System,
}

impl From<Role> for LlmRole {
    fn from(r: Role) -> Self {
        match r {
            Role::User => LlmRole::User,
            Role::Assistant => LlmRole::Assistant,
            Role::System => LlmRole::System,
        }
    }
}

// ── Message ───────────────────────────────────────────────────────────────────

/// A single stored conversation turn.
///
/// Maps 1:1 to the `messages` array sent to the LLM provider.
/// Tool call round-trips are not stored — only the final text turns are.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Who produced this turn.
    pub role: Role,
    /// Text content of the turn.
    pub content: String,
}

impl Message {
    /// Converts this stored message into a [`ChatMessage`] suitable for LLM requests.
    pub fn to_chat_message(&self) -> ChatMessage {
        ChatMessage {
            role: self.role.clone().into(),
            content: self.content.clone(),
            tool_calls: vec![],
            tool_call_id: None,
        }
    }
}

// ── SessionStore trait ────────────────────────────────────────────────────────

/// Pluggable storage backend for conversation history.
///
/// Implementors can back this with in-memory state, files, Redis, Postgres,
/// or any async store. The trait uses `Pin<Box<dyn Future>>` for object safety.
///
/// Built-in implementations:
/// - [`MemorySessionStore`] — in-process `HashMap`, used for CLI and tests.
/// - `FileSessionStore` — one JSON file per session, used for HTTP server mode.
pub trait SessionStore: Send + Sync + 'static {
    /// Loads the conversation history for `session_id`.
    ///
    /// Returns an empty `Vec` if the session does not exist.
    fn load<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<Message>, SessionError>> + Send + 'a>>;

    /// Persists the conversation history for `session_id`.
    ///
    /// Overwrites any existing history for this session.
    fn save<'a>(
        &'a self,
        session_id: &'a str,
        history: &'a [Message],
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>>;

    /// Removes all stored history for `session_id`.
    ///
    /// Does nothing if the session does not exist.
    fn delete<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>>;
}

// ── MemorySessionStore ────────────────────────────────────────────────────────

/// In-memory session store backed by a `HashMap`.
///
/// The default for CLI mode and tests. Sessions are lost when the process exits.
#[derive(Debug, Default)]
pub struct MemorySessionStore {
    inner: Arc<Mutex<HashMap<String, Vec<Message>>>>,
}

impl MemorySessionStore {
    /// Creates a new, empty in-memory session store.
    pub fn new() -> Self {
        Self::default()
    }
}

impl SessionStore for MemorySessionStore {
    fn load<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<Message>, SessionError>> + Send + 'a>> {
        Box::pin(async move {
            let map = self.inner.lock().await;
            Ok(map.get(session_id).cloned().unwrap_or_default())
        })
    }

    fn save<'a>(
        &'a self,
        session_id: &'a str,
        history: &'a [Message],
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>> {
        Box::pin(async move {
            let mut map = self.inner.lock().await;
            map.insert(session_id.to_string(), history.to_vec());
            Ok(())
        })
    }

    fn delete<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>> {
        Box::pin(async move {
            let mut map = self.inner.lock().await;
            map.remove(session_id);
            Ok(())
        })
    }
}

// ── FileSessionStore ──────────────────────────────────────────────────────────

/// File-backed session store that persists one JSON file per session.
///
/// Each session is stored as `{dir}/{session_id}.json`, containing a JSON
/// array of [`Message`] objects. Suitable for HTTP server mode where sessions
/// must survive process restarts.
///
/// # Session ID safety
///
/// Session IDs are validated before use. IDs containing `/`, `\`, `..`, or
/// null bytes are rejected with [`SessionError::Invalid`] to prevent path
/// traversal attacks.
pub struct FileSessionStore {
    dir: PathBuf,
}

impl FileSessionStore {
    /// Creates a new `FileSessionStore` rooted at `dir`.
    ///
    /// The directory need not exist yet; it will be created on the first
    /// [`save`](SessionStore::save) call.
    pub fn new(dir: impl AsRef<Path>) -> Self {
        Self { dir: dir.as_ref().to_path_buf() }
    }

    /// Validates a session ID and returns the corresponding file path.
    fn session_path(&self, session_id: &str) -> Result<PathBuf, SessionError> {
        // Reject IDs containing dangerous characters or sequences.
        if session_id.contains('/')
            || session_id.contains('\\')
            || session_id.contains("..")
            || session_id.contains('\0')
        {
            return Err(SessionError::Invalid(format!(
                "session_id {:?} contains forbidden characters",
                session_id
            )));
        }
        Ok(self.dir.join(format!("{session_id}.json")))
    }
}

impl SessionStore for FileSessionStore {
    fn load<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<Vec<Message>, SessionError>> + Send + 'a>> {
        Box::pin(async move {
            let path = self.session_path(session_id)?;
            match tokio::fs::read(&path).await {
                Ok(bytes) => {
                    let messages: Vec<Message> = serde_json::from_slice(&bytes)
                        .map_err(|e| SessionError::Serialization(e.to_string()))?;
                    Ok(messages)
                }
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(vec![]),
                Err(e) => Err(SessionError::Io(e)),
            }
        })
    }

    fn save<'a>(
        &'a self,
        session_id: &'a str,
        history: &'a [Message],
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>> {
        Box::pin(async move {
            let path = self.session_path(session_id)?;
            // Ensure the directory exists.
            if let Some(parent) = path.parent() {
                tokio::fs::create_dir_all(parent).await?;
            }
            let json = serde_json::to_vec(history)
                .map_err(|e| SessionError::Serialization(e.to_string()))?;
            tokio::fs::write(&path, &json).await?;
            Ok(())
        })
    }

    fn delete<'a>(
        &'a self,
        session_id: &'a str,
    ) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send + 'a>> {
        Box::pin(async move {
            let path = self.session_path(session_id)?;
            match tokio::fs::remove_file(&path).await {
                Ok(()) => Ok(()),
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
                Err(e) => Err(SessionError::Io(e)),
            }
        })
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn msg(role: Role, content: &str) -> Message {
        Message { role, content: content.into() }
    }

    #[tokio::test]
    async fn memory_store_load_save_delete_round_trip() {
        let store = MemorySessionStore::new();

        // Load non-existent session → empty vec
        let history = store.load("s1").await.unwrap();
        assert!(history.is_empty());

        // Save a conversation
        let turns = vec![
            msg(Role::User, "Hello"),
            msg(Role::Assistant, "Hi there!"),
        ];
        store.save("s1", &turns).await.unwrap();

        // Load it back
        let loaded = store.load("s1").await.unwrap();
        assert_eq!(loaded.len(), 2);
        assert_eq!(loaded[0].content, "Hello");
        assert_eq!(loaded[1].content, "Hi there!");

        // Different session is independent
        let other = store.load("s2").await.unwrap();
        assert!(other.is_empty());

        // Delete
        store.delete("s1").await.unwrap();
        let after_delete = store.load("s1").await.unwrap();
        assert!(after_delete.is_empty());

        // Delete non-existent is a no-op
        store.delete("s99").await.unwrap();
    }

    #[test]
    fn message_converts_to_chat_message() {
        let m = msg(Role::User, "test");
        let cm = m.to_chat_message();
        assert!(matches!(cm.role, LlmRole::User));
        assert_eq!(cm.content, "test");
        assert!(cm.tool_calls.is_empty());
    }

    // ── FileSessionStore tests ─────────────────────────────────────────────

    #[tokio::test]
    async fn file_store_save_and_load_round_trip() {
        let dir = tempfile::tempdir().expect("tempdir");
        let store = FileSessionStore::new(dir.path());

        let turns = vec![
            msg(Role::User, "hello"),
            msg(Role::Assistant, "hi"),
        ];
        store.save("sess1", &turns).await.unwrap();

        let loaded = store.load("sess1").await.unwrap();
        assert_eq!(loaded.len(), 2);
        assert!(matches!(loaded[0].role, Role::User));
        assert_eq!(loaded[0].content, "hello");
        assert!(matches!(loaded[1].role, Role::Assistant));
        assert_eq!(loaded[1].content, "hi");
    }

    #[tokio::test]
    async fn file_store_load_missing_session_returns_empty() {
        let dir = tempfile::tempdir().expect("tempdir");
        let store = FileSessionStore::new(dir.path());

        let result = store.load("nonexistent").await.unwrap();
        assert!(result.is_empty());
    }

    #[tokio::test]
    async fn file_store_delete_removes_file() {
        let dir = tempfile::tempdir().expect("tempdir");
        let store = FileSessionStore::new(dir.path());

        let turns = vec![msg(Role::User, "bye")];
        store.save("to_delete", &turns).await.unwrap();

        // Confirm it exists first
        let before = store.load("to_delete").await.unwrap();
        assert_eq!(before.len(), 1);

        store.delete("to_delete").await.unwrap();

        let after = store.load("to_delete").await.unwrap();
        assert!(after.is_empty());

        // Deleting again (already missing) should be a no-op
        store.delete("to_delete").await.unwrap();
    }

    #[tokio::test]
    async fn file_store_rejects_path_traversal() {
        let dir = tempfile::tempdir().expect("tempdir");
        let store = FileSessionStore::new(dir.path());

        let result = store.load("../evil").await;
        assert!(matches!(result, Err(SessionError::Invalid(_))));

        let result2 = store.save("../../etc/passwd", &[]).await;
        assert!(matches!(result2, Err(SessionError::Invalid(_))));
    }
}
